import { User } from '../../users/user.entity';
export const MOCK_USERS: Partial<User>[] = [
  { firstName:"Howey", lastName:"Cockburn", email:"hcockburn0@hp.com" } as Partial<User>,
  { firstName:"Stephie", lastName:"Drowsfield", email:"sdrowsfield1@usatoday.com" } as Partial<User>,
  { firstName:"Julita", lastName:"Thomann", email:"jthomann2@thetimes.co.uk" } as Partial<User>,
  { firstName:"Anthiathia", lastName:"Ewbanke", email:"aewbanke3@privacy.gov.au" } as Partial<User>,
  { firstName:"Gaby", lastName:"Tregien", email:"gtregien4@ehow.com" } as Partial<User>,
  { firstName:"Reidar", lastName:"McTavish", email:"rmctavish5@weather.com" } as Partial<User>,
  { firstName:"Tiler", lastName:"Fagge", email:"tfagge6@smugmug.com" } as Partial<User>,
  { firstName:"Falkner", lastName:"Paoli", email:"fpaoli7@geocities.jp" } as Partial<User>,
  { firstName:"Anthe", lastName:"Heed", email:"aheed8@networksolutions.com" } as Partial<User>,
  { firstName:"Grayce", lastName:"Tollit", email:"gtollit9@timesonline.co.uk" } as Partial<User>,
  { firstName:"Janek", lastName:"Milne", email:"jmilnea@cam.ac.uk" } as Partial<User>,
  { firstName:"Ingram", lastName:"Fairbeard", email:"ifairbeardb@domainmarket.com" } as Partial<User>,
  { firstName:"Jephthah", lastName:"Thorp", email:"jthorpc@parallels.com" } as Partial<User>,
  { firstName:"Ashby", lastName:"Holston", email:"aholstond@deviantart.com" } as Partial<User>,
  { firstName:"Calla", lastName:"Pietesch", email:"cpietesche@yellowpages.com" } as Partial<User>,
  { firstName:"Marris", lastName:"Kinforth", email:"mkinforthf@ucsd.edu" } as Partial<User>,
  { firstName:"Prissie", lastName:"Vergine", email:"pvergineg@forbes.com" } as Partial<User>,
  { firstName:"Valene", lastName:"Lownds", email:"vlowndsh@geocities.com" } as Partial<User>,
  { firstName:"Norina", lastName:"Archard", email:"narchardi@multiply.com" } as Partial<User>,
  { firstName:"Brinn", lastName:"Giacopetti", email:"bgiacopettij@utexas.edu" } as Partial<User>,
  { firstName:"Ev", lastName:"Bolden", email:"eboldenk@shareasale.com" } as Partial<User>,
  { firstName:"Wyn", lastName:"Foxall", email:"wfoxalll@furl.net" } as Partial<User>,
  { firstName:"Alexandre", lastName:"Everett", email:"aeverettm@ucoz.ru" } as Partial<User>,
  { firstName:"Keane", lastName:"Holbie", email:"kholbien@unicef.org" } as Partial<User>,
  { firstName:"Jana", lastName:"Abbott", email:"jabbotto@xinhuanet.com" } as Partial<User>,
  { firstName:"Ansley", lastName:"Shitliffe", email:"ashitliffep@joomla.org" } as Partial<User>,
  { firstName:"Ralf", lastName:"Filippello", email:"rfilippelloq@twitpic.com" } as Partial<User>,
  { firstName:"Clay", lastName:"Belding", email:"cbeldingr@live.com" } as Partial<User>,
  { firstName:"Kingsly", lastName:"Frearson", email:"kfrearsons@upenn.edu" } as Partial<User>,
  { firstName:"Boyd", lastName:"Tisun", email:"btisunt@yale.edu" } as Partial<User>
]
